name: CI/CD Pipeline NextJS 14

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/nexis
            git pull origin main
            npm ci
            npm run build --trace-warnings=false
            pm2 restart all || pm2 start npm --name "nexis" -- start
